url = "http://mobilewzrc.serverroom.us:6916/"
database_name = "example_am1430"
language="yue"
operation = "transcribe" # or save_to_file
show_name = "am1430"

[database_config]
database_host = "10.22.33.120"
database_user = "postgres"
database_port = 5432
database_password_key = "postgres_portainer"
database_name = "example_am1430"
require_ssl=false