
# https://github.com/junguler/m3u-radio-music-playlists/blob/403134e0e43c7cf16d76d33278197b9fda7cf57e/radio_station_usa.fm/news.m3u#L6
url = "https://live.amperwave.net/manifest/audacy-knxamaac-imc"
language="en"
show_name = "knx_news"

[database_config]
database_host = "10.22.33.120"
database_user = "postgres"
database_port = 5432
database_password_key = "postgres_portainer"
database_name = "whisper_transcribe_rs_v1"
require_ssl=false

# [database_config]
# database_host = "us-west-2.sql.xata.sh"
# database_user = "mo4dsg"
# database_port = 5432
# database_password_key = "postgres_xata"
# database_name = "my-database:main"
# require_ssl=true