url = "audio_output://default"
language="yue" #cantonese
show_name = "audio_output"

# [database_config]
# database_host = "10.22.33.120"
# database_user = "postgres"
# database_port = 5432
# database_password_key = "postgres_portainer"
# database_name = "whisper_transcribe_rs_v1"
# require_ssl=false